#!/usr/bin/env python3
"""
MechForge GUI 独立启动器
直接运行此文件即可启动完整的 GUI 应用
"""

import os
import sys
import json
import argparse
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import threading

# 添加项目根目录到 Python 路径
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, PROJECT_ROOT)


class GUIServerHandler(SimpleHTTPRequestHandler):
    """自定义 HTTP 处理器，提供 API 和静态文件服务"""

    # CORS 头
    CORS_HEADERS = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
    }

    def __init__(self, *args, directory=None, **kwargs):
        self.gui_directory = PROJECT_ROOT
        super().__init__(*args, directory=self.gui_directory, **kwargs)

    def do_OPTIONS(self):
        """处理 CORS 预检请求"""
        self.send_response(200)
        for header, value in self.CORS_HEADERS.items():
            self.send_header(header, value)
        self.end_headers()

    def do_GET(self):
        """处理 GET 请求"""
        path = urlparse(self.path).path

        # API 端点
        if path.startswith('/api/'):
            self.handle_api_get(path)
            return

        # 默认静态文件服务
        super().do_GET()

    def do_POST(self):
        """处理 POST 请求"""
        path = urlparse(self.path).path
        content_length = int(self.headers.get('Content-Length', 0))
        body = self.rfile.read(content_length).decode('utf-8')

        # 解析 JSON
        try:
            data = json.loads(body) if body else {}
        except json.JSONDecodeError:
            data = {}

        # API 端点
        if path.startswith('/api/'):
            self.handle_api_post(path, data)
            return

        self.send_error(400, 'Invalid request')

    def send_json_response(self, data, status=200):
        """发送 JSON 响应"""
        self.send_response(status)
        for header, value in self.CORS_HEADERS.items():
            self.send_header(header, value)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(data).encode('utf-8'))

    def handle_api_get(self, path):
        """处理 GET API 请求"""
        if path == '/api/config':
            # 返回默认配置
            self.send_json_response({
                'ai': {
                    'provider': 'ollama',
                    'model': 'qwen2.5:3b'
                },
                'rag': {
                    'enabled': True,
                    'backend': 'local',
                    'top_k': 5
                },
                'ui': {
                    'theme': 'dark',
                    'language': 'zh-CN'
                }
            })
        elif path == '/api/models':
            self.send_json_response([
                {'name': 'qwen2.5:3b', 'provider': 'ollama'},
                {'name': 'llama3:8b', 'provider': 'ollama'},
                {'name': 'gpt-4o', 'provider': 'openai'},
            ])
        elif path == '/api/status':
            self.send_json_response({
                'status': 'ready',
                'version': '0.5.0'
            })
        elif path == '/api/rag/status':
            self.send_json_response({
                'enabled': True,
                'backend': 'local',
                'doc_count': 0
            })
        else:
            self.send_error(404, 'API endpoint not found')

    def handle_api_post(self, path, data):
        """处理 POST API 请求"""
        if path == '/api/chat':
            # AI 对话 - 模拟响应
            message = data.get('message', '')
            rag_enabled = data.get('rag', False)

            # 构建响应
            responses = [
                f"Processing query: \"{message}\"\n> Analysis complete. RAG retrieval {'active' if rag_enabled else 'inactive'}.\nResponse generated by qwen2.5:3b.",
                f"Analyzing your request: \"{message}\"\n> Context retrieved from knowledge base.\nGenerating response...",
                f"Query received: \"{message}\"\n> Searching relevant information...\nResults found and synthesized.",
                f"Your query \"{message}\" has been processed.\n> Engaging AI model for response...\nDone."
            ]
            import random
            response = random.choice(responses)

            self.send_json_response({
                'response': response,
                'model': 'qwen2.5:3b',
                'rag_used': rag_enabled
            })

        elif path == '/api/rag/search':
            # RAG 搜索 - 模拟响应
            query = data.get('query', '')
            limit = data.get('limit', 5)

            # 模拟搜索结果
            results = [
                {
                    'title': f'Result {i+1} for "{query}"',
                    'content': f'This is a simulated knowledge base result for the query: {query}. In a real implementation, this would connect to the RAG engine.',
                    'score': 0.95 - (i * 0.1),
                    'source': 'knowledge_base'
                }
                for i in range(min(limit, 3))
            ]

            self.send_json_response(results)

        elif path == '/api/rag/toggle':
            enabled = data.get('enabled', False)
            self.send_json_response({'enabled': enabled})

        elif path == '/api/config':
            self.send_json_response({'success': True})

        else:
            self.send_error(404, 'API endpoint not found')


def run_server(port=5000):
    """启动服务器"""
    os.chdir(PROJECT_ROOT)

    server = HTTPServer(('127.0.0.1', port), GUIServerHandler)

    print("""
============================================================
                    MechForge AI v0.5.0
                     GUI 独立启动器
============================================================

   [GUI] http://127.0.0.1:{}

   功能:
   * AI 对话 (模拟响应)
   * 知识库搜索 (模拟结果)
   * CAE 工作台 (演示模式)

   按 Ctrl+C 停止服务器

============================================================
    """.format(port))

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n\n正在关闭服务器...")
        server.shutdown()
        print("服务器已关闭。")


def main():
    parser = argparse.ArgumentParser(description='MechForge GUI 独立启动器')
    parser.add_argument('-p', '--port', type=int, default=5000,
                        help='服务器端口 (默认: 8080)')
    parser.add_argument('--host', default='127.0.0.1',
                        help='服务器地址 (默认: 127.0.0.1)')

    args = parser.parse_args()

    # 修改服务器地址
    global GUIServerHandler
    class CustomHandler(GUIServerHandler):
        pass

    # 重新定义 run_server 使用自定义参数
    def run_custom_server(port):
        os.chdir(PROJECT_ROOT)
        server = HTTPServer(('127.0.0.1', port), CustomHandler)
        print("""
============================================================
                    MechForge AI v0.5.0
                     GUI 独立启动器
============================================================

   [GUI] http://127.0.0.1:{}

   功能:
   * AI 对话 (模拟响应)
   * 知识库搜索 (模拟结果)
   * CAE 工作台 (演示模式)

   按 Ctrl+C 停止服务器

============================================================
        """.format(port))
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            print("\n\n正在关闭服务器...")
            server.shutdown()
            print("服务器已关闭。")

    run_custom_server(args.port)


if __name__ == '__main__':
    main()
